services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: management
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
