// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (id, account_id, card_number, expiry_date, pin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, card_number, expiry_date, pin, created_at
`

type CreateCardParams struct {
	ID         string      `json:"id"`
	AccountID  string      `json:"account_id"`
	CardNumber int32       `json:"card_number"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
	Pin        int32       `json:"pin"`
}

// Create card for an account
func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.AccountID,
		arg.CardNumber,
		arg.ExpiryDate,
		arg.Pin,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CardNumber,
		&i.ExpiryDate,
		&i.Pin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE id = $1
`

// delete card by ID
func (q *Queries) DeleteCard(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, account_id, card_number, expiry_date, pin, created_at
FROM cards
WHERE id = $1
`

// get card by ID
func (q *Queries) GetCardByID(ctx context.Context, id string) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CardNumber,
		&i.ExpiryDate,
		&i.Pin,
		&i.CreatedAt,
	)
	return i, err
}

const getCardsByAccountID = `-- name: GetCardsByAccountID :many
SELECT id, account_id, card_number, expiry_date, pin, created_at
FROM cards
WHERE account_id = $1
`

// get cards by account ID
func (q *Queries) GetCardsByAccountID(ctx context.Context, accountID string) ([]Card, error) {
	rows, err := q.db.Query(ctx, getCardsByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CardNumber,
			&i.ExpiryDate,
			&i.Pin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
