// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Balance   pgtype.Numeric `json:"balance"`
	CreatedAt time.Time      `json:"created_at"`
}

type Card struct {
	ID         string      `json:"id"`
	AccountID  string      `json:"account_id"`
	CardNumber int32       `json:"card_number"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
	Pin        int32       `json:"pin"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Transaction struct {
	ID                string         `json:"id"`
	SenderAccountID   string         `json:"sender_account_id"`
	ReceiverAccountID string         `json:"receiver_account_id"`
	Amount            pgtype.Numeric `json:"amount"`
	CreatedAt         time.Time      `json:"created_at"`
}

type User struct {
	ID        string    `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
}
