// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	// Create new account
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// Create card for an account
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	// Create transaction entry
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	// Create new user
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Delete account
	DeleteAccount(ctx context.Context, id string) error
	// delete card by ID
	DeleteCard(ctx context.Context, id string) error
	// Delete user
	DeleteUser(ctx context.Context, id string) error
	// Get account by ID
	GetAccountByID(ctx context.Context, id string) (Account, error)
	// Lock account row for transaction
	GetAccountForUpdate(ctx context.Context, id string) (Account, error)
	// Get accounts by user ID
	GetAccountsByUserID(ctx context.Context, userID string) ([]Account, error)
	// get card by ID
	GetCardByID(ctx context.Context, id string) (Card, error)
	// get cards by account ID
	GetCardsByAccountID(ctx context.Context, accountID string) ([]Card, error)
	// Get transaction by ID
	GetTransactionByID(ctx context.Context, id string) (Transaction, error)
	// Get transactions by sender account ID
	GetTransactionsByAccountID(ctx context.Context, senderAccountID string) ([]Transaction, error)
	// Get transactions by receiver account ID
	GetTransactionsByReceiverAccountID(ctx context.Context, receiverAccountID string) ([]Transaction, error)
	// Get user by email
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Get user by ID
	GetUserByID(ctx context.Context, id string) (User, error)
	// Get user by phone
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	// Update account balance
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	// Update User
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
