// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transfer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id,
    sender_account_id,
    receiver_account_id,    
    amount,
    created_at
)
VALUES ($1, $2, $3, $4, now())
RETURNING id, sender_account_id, receiver_account_id, amount, created_at
`

type CreateTransactionParams struct {
	ID                string         `json:"id"`
	SenderAccountID   string         `json:"sender_account_id"`
	ReceiverAccountID string         `json:"receiver_account_id"`
	Amount            pgtype.Numeric `json:"amount"`
}

// Create transaction entry
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.SenderAccountID,
		arg.ReceiverAccountID,
		arg.Amount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SenderAccountID,
		&i.ReceiverAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, sender_account_id, receiver_account_id, amount, created_at
FROM transactions
WHERE id = $1
`

// Get transaction by ID
func (q *Queries) GetTransactionByID(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.SenderAccountID,
		&i.ReceiverAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionsByAccountID = `-- name: GetTransactionsByAccountID :many
SELECT id, sender_account_id, receiver_account_id, amount, created_at
FROM transactions
WHERE sender_account_id = $1
ORDER BY created_at DESC
`

// Get transactions by sender account ID
func (q *Queries) GetTransactionsByAccountID(ctx context.Context, senderAccountID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByAccountID, senderAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.SenderAccountID,
			&i.ReceiverAccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByReceiverAccountID = `-- name: GetTransactionsByReceiverAccountID :many
SELECT id, sender_account_id, receiver_account_id, amount, created_at
FROM transactions
WHERE receiver_account_id = $1  
ORDER BY created_at DESC
`

// Get transactions by receiver account ID
func (q *Queries) GetTransactionsByReceiverAccountID(ctx context.Context, receiverAccountID string) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByReceiverAccountID, receiverAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.SenderAccountID,
			&i.ReceiverAccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
